#!/bin/bash
# autopkgtest check: Run the installed-tests to verify e-d-s works correctly
# (C) 2013-2015 Canonical Ltd.
# Author: Iain Lane <iain.lane@canonical.com>
set -e

export XDG_RUNTIME_DIR=$AUTOPKGTEST_TMP

# dbus outputs activation messages to stderr which fails the test
dbus-run-session -- xvfb-run -a gnome-desktop-testing-runner --parallel=1 evolution-data-server 2> >(grep -vE '^(Activating|Successfully activated)')>&2
